# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Format prompt: Left side | Right side (via $fill)
format = """
$directory $golang$nodejs$python$lua$git_branch$git_status$fill$cmd_duration$gcloud$kubernetes$terraform$time
$character"""

# Dynamic palette based on OS Dark/Light mode (exported by Fish as $DEFAULT_THEME)
palette = "catppuccin-macchiato"

# Modules
[directory]
style = "fg:text bg:background"
format = '[$path]($style) '
truncation_length = 1
truncation_symbol = "~/../"

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
format = "$symbol "

[fill]
symbol = " "
style = "fg:surface0"

[git_branch]
style = "fg:peach bg:background"
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = "fg:red bg:background"
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "​= "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "​?${count} "
stashed = "​$ "
modified = "​!${count} "
staged = "​+${count} "
renamed = "​»${count} "
deleted = "​✘${count} "

[golang]
style = "fg:teal bg:background"
format = "[\ue627 $version]($style) [-](fg:surface0) "
detect_extensions = ["go"]
detect_files = ["go.mod", "go.sum", "go.work"]
detect_folders = ["Godeps"]

[nodejs]
style = "fg:teal bg:background"
format = "[\ue718 $version]($style) [-](fg:surface0) "
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts"]
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_folders = ["node_modules"]

[python]
style = "fg:teal bg:background"
format = "[\ue606 $version]($style) [-](fg:surface0) "
detect_extensions = ["py"]
detect_files = [
  ".python-version",
  "Pipfile",
  "pyproject.toml",
  "requirements.txt",
  "setup.py",
  "tox.ini",
]

[lua]
style = "fg:teal bg:background"
format = "[\ue620 $version]($style) [-](fg:surface0) "
detect_extensions = ["lua"]
detect_files = [".lua-version"]
detect_folders = ["lua"]

## Right modules
[cmd_duration]
style = "fg:yellow bg:background"
format = "[  $duration]($style) [-](fg:surface0) "
min_time = 1_000

[gcloud]
style = "fg:blue bg:background"
format = "[󱇶 $project]($style) [-](fg:surface0) "

[kubernetes]
style = "fg:sky bg:background"
format = "[󱃾 $context(/$namespace)]($style) [-](fg:surface0) "
disabled = false

[terraform]
style = "fg:mauve bg:background"
format = "[󱁢 $workspace]($style) [-](fg:surface0) "

[time]
style = "fg:green bg:background"
format = "[\ue383 $time]($style)"
time_format = "%H:%M:%S"
disabled = false

# Define color palette
[palettes.catppuccin-macchiato]
background = "transparent"
blue = "#8aadf4"
green = "#a6da95"
maroon = "#ee99a0"
mauve = "#c6a0f6"
peach = "#f5a97f"
red = "#ed8796"
sky = "#91d7e3"
surface0 = "#363a4f"
teal = "#8bd5ca"
text = "#cad3f5"
yellow = "#eed49f"

[palettes.catppuccin-latte]
background = "transparent"
blue = "#1e66f5"
green = "#40a02b"
maroon = "#e64553"
mauve = "#8839ef"
peach = "#fe640b"
red = "#d20f39"
sky = "#04a5e5"
surface0 = "#ccd0da"
teal = "#179299"
text = "#4c4f69"
yellow = "#df8e1d"
